config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :profolios
  resources :services
  get 'pages/info'
  get "pages/info"
  resources :ideas
  root :to => redirect('/ideas')

end

app/models/idea.rb
class Idea < ActiveRecord::Base
mount_uploader :picture, PictureUploader
end

app/models/profolio.rb
class Profolio < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/controllers/profolios_controller.rb
class ProfoliosController < ApplicationController
  before_action :set_profolio, only: [:show, :edit, :update, :destroy]

  # GET /profolios
  # GET /profolios.json
  def index
    @profolios = Profolio.all
  end

  # GET /profolios/1
  # GET /profolios/1.json
  def show
  end

  # GET /profolios/new
  def new
    @profolio = Profolio.new
  end

  # GET /profolios/1/edit
  def edit
  end

  # POST /profolios
  # POST /profolios.json
  def create
    @profolio = Profolio.new(profolio_params)

    respond_to do |format|
      if @profolio.save
        format.html { redirect_to @profolio, notice: 'Profolio was successfully created.' }
        format.json { render :show, status: :created, location: @profolio }
      else
        format.html { render :new }
        format.json { render json: @profolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profolios/1
  # PATCH/PUT /profolios/1.json
  def update
    respond_to do |format|
      if @profolio.update(profolio_params)
        format.html { redirect_to @profolio, notice: 'Profolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @profolio }
      else
        format.html { render :edit }
        format.json { render json: @profolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profolios/1
  # DELETE /profolios/1.json
  def destroy
    @profolio.destroy
    respond_to do |format|
      format.html { redirect_to profolios_url, notice: 'Profolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profolio
      @profolio = Profolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profolio_params
      params.require(:profolio).permit(:name, :password, :stocks)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params[:service]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profolios_helper.rb
module ProfoliosHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/ideas/_form.html.erb
<%= form_for @idea, :html => {:multipart => true} do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h2>Editing Idea</h2>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h2>Listing ideas</h2>

<% @ideas.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |idea| %>
      <div class="col-md-4">
        <%= image_tag idea.picture_url, width: '100%' if idea.picture.present?%>
        <h4><%= link_to idea.name, idea %></h4>
        <%= idea.description %>
      </div>
    <% end %>
  </div>
  <div id="blueimp-gallery" class="blueimp-gallery">
			<!-- The container for the modal slides -->
			<div class="slides"></div>
			<!-- Controls for the borderless lightbox -->
			<h3 class="title"></h3>
			<a class="prev">‹</a>
			<a class="next">›</a>
			<a class="close">×</a>
			<a class="play-pause"></a>
			<ol class="indicator"></ol>
			<!-- The modal dialog, which will be used to wrap the lightbox content -->
			<div class="modal fade">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" aria-hidden="true">
								&times;
							</button>
							<h4 class="modal-title"></h4>
						</div>
						<div class="modal-body next"></div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default pull-left prev">
								<i class="glyphicon glyphicon-chevron-left"></i>
								Previous
							</button>
							<button type="button" class="btn btn-primary next">
								Next
								<i class="glyphicon glyphicon-chevron-right"></i>
							</button>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div id="jquery_gallery">
			<a href="/images/img1.jpg" data-gallery> <img src="/images/img1.jpg" /> </a>
			<a href="/images/img2.jpg" data-gallery> <img src="/images/img2.jpg" /> </a>
			<a href="/images/img3.jpg" data-gallery> <img src="/images/img3.jpg" /> </a>
			<a href="/images/img4.jpg" data-gallery> <img src="/images/img4.jpg" /> </a>
			<a href="/images/img5.jpg" data-gallery> <img src="/images/img5.jpg" /> </a>

		</div>
<% end %>

app/views/ideas/new.html.erb
<h2>New Idea</h2>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-9">
    <%= image_tag(@idea.picture_url, width: '100%') if @idea.picture.present? %>
  </div>

  <div class="col-md-3">
    <p><b>Name: </b><%= @idea.name %></p>
    <p><b>Description: </b><%= @idea.description %></p>
    <p>
      <%= link_to 'Edit', edit_idea_path(@idea) %> |
      <%= link_to 'Destroy', @idea, data: { confirm: 'Are you sure?' }, method: :delete %> |
      <%= link_to 'Back', ideas_path %>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Alex</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.5.3/slick.css"/>
		<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.5.3/slick-theme.css"/>
		<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.5.0/slick.css"/>
		<link rel="stylesheet" type="text/css" href="slick/slick.css"/>

		<link rel="stylesheet" type="text/css" href="slick/slick-theme.css"/>

		<link rel="stylesheet" type="text/css" href='http://fonts.googleapis.com/css?family=Lobster|Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
		<link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">

		<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="http://blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
		<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.5.0/slick.min.js"></script>
		<!-- <link rel="stylesheet" href="javascripts/jqueryGallery/css/bootstrap-image-gallery.min.css"> -->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
		<script src="http://blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
		<!-- <script src="js/bootstrap-image-gallery.min.js"></script> -->
		<%= javascript_include_tag "vendor/modernizr"%>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<style>
			h1 {
				font-family: 'Lobster', cursive;
				color: black;
				font-size: 88px;
				background-color: #F8F8F8;
			}
			h2 {
				font-family: 'Open Sans Condensed', sans-serif;
				font-size: 26px;
			}
			h3 {
				font-family: 'Open Sans Condensed', sans-serif;
				font-size: 20px;
				background-color: #F8F8F8;
			}

			#jquery_gallery a {
				display: inline;
			}
			#jquery_gallery a img {
				width: 160px;
				height: 100px;
			}
		</style>
	</head>
	<body>
		<h1>Welcome to Personal Finance </h1>
		<h2>Free service to make smarter decision</h2>
		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>

					<a class="navbar-brand" href="/">Personal Finance Shop</a>
				</div>
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
						<li >
							<%= link_to 'New Idea',new_idea_path %>
						</li>
						<li>
							<%= link_to 'Free Service',new_service_path %>
						</li>
						<li>
							<%= link_to 'My profile',new_profolio_path %>
							</li>
							</ul>
							</div>
							</div>
							</nav>
							<div class="your-class">
								<div>
									<img src="/images/img3.jpg"  alt="image3">
									<h3>
									 Best financial risk management by providing free personal stock updates, making smarter choices.
									</h3>
								</div>
								<div>
									<img src="/images/img4.jpg"  alt="image4">
									<h3>
								 Get any loan you want in a convient way by our professional advisors and find your perfect work-life balance 
									</h3>
								</div>
								<div>
									<img src="/images/img5.jpg"  alt="image5">
									<h3>
									Project management team insurance your banking and peronal investment dicisions.
									</h3>
								</div>
							</div>

							<div class="container">
								<%= yield %>
							</div>

							<footer>
								<div class="container">
	Rails Girls Chenzi2015
				</div>
			</footer>
			<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.5.3/slick.min.js"></script>
			<script src="jquery.js"></script>
			<script src="jquery.sticky.js"></script>
			<script src="//railsgirls.com/assets/bootstrap.js"></script>
		<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
		<script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
		<script type="text/javascript" src="slick/slick.min.js"></script>

		<script type="text/javascript">
			$('.your-class').slick({
				dots : true,
				infinite : true,
				speed : 300,
				slidesToShow : 1,
				adaptiveHeight : true

			});

		</script>
		</body>
		</html>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>

app/views/profolios/_form.html.erb
<%= form_for(@profolio) do |f| %>
  <% if @profolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profolio.errors.count, "error") %> prohibited this profolio from being saved:</h2>

      <ul>
      <% @profolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :stocks %><br>
    <%= f.text_field :stocks %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profolios/edit.html.erb
<h2>Editing Profolio</h2>

<%= render 'form' %>

<%= link_to 'Show', @profolio %> |
<%= link_to 'Back', profolios_path %>

app/views/profolios/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Listing Profolios</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th>Stocks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profolios.each do |profolio| %>
      <tr>
        <td><%= profolio.name %></td>
        <td><%= profolio.password %></td>
        <td><%= profolio.stocks %></td>
        <td><%= link_to 'Show', profolio %></td>
        <td><%= link_to 'Edit', edit_profolio_path(profolio) %></td>
        <td><%= link_to 'Destroy', profolio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profolio', new_profolio_path %>

app/views/profolios/new.html.erb
<h2>New Profolio</h2>

<%= render 'form' %>

<%= link_to 'Back', profolios_path %>

app/views/profolios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @profolio.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @profolio.password %>
</p>

<p>
  <strong>Stocks:</strong>
  <%= @profolio.stocks %>
</p>

<%= link_to 'Edit', edit_profolio_path(@profolio) %> |
<%= link_to 'Back', profolios_path %>

app/views/services/edit.html.erb
<h2>Editing Service</h2>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Our Service</h2>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h2>our Service</h2>
<p>We provide you a platfrom with sharing and inspiration.</p>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>